packages:
  - apps/*
  - sdk
  - packages/*
  - scripts/*

$schema: https://www.schemastore.org/pnpm-workspace.json

catalog:
  '@ant-design/icons': ^6.1.0
  '@ant-design/pro-components': ^3.0.2-0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  antd: ^6.1.0
  oxlint: ^1.32.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router: ^7.10.1
