packages:
  - apps/*
  - sdk
  - packages/*
  - scripts/*

catalog:
  '@ant-design/icons': ^6.3.2
  '@ant-design/pro-components': ^3.1.12-0
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  antd: ^6.5.0
  axios: ^1.13.2
  dayjs: ^1.11.21
  i18next: ^26.3.4
  i18next-http-backend: ^4.0.0
  oxfmt: ^0.57.0
  oxlint: ^1.72.0
  react: ^19.2.7
  react-dom: ^19.2.7
  react-i18next: ^17.0.8
  react-router: ^8.1.0

allowBuilds:
  core-js: false
  esbuild: true
