$schema: https://www.schemastore.org/pnpm-workspace.json

packages:
  - apps/*
  - sdk
  - packages/*
  - scripts/*

catalog:
  '@ant-design/icons': ^6.1.0
  '@ant-design/pro-components': ^3.1.0-0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  antd: ^6.1.2
  axios: ^1.13.2
  dayjs: ^1.11.19
  oxlint: ^1.35.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router: ^7.11.0
